In [14]:
import sys


In [16]:
!{sys.executable} -m pip install numpy 

In [19]:
# ex1
import numpy as np

arr1 = np.arange(1, 11)
arr1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# ex2
arr2 = np.random.randint(1, 10, size=(3, 3))
arr2


array([[8, 7, 8],
       [5, 7, 1],
       [2, 9, 3]], dtype=int32)

In [21]:
# ex3
arr1.sum(), arr1.mean(), arr1.max()

(np.int64(55), np.float64(5.5), np.int64(10))

In [22]:
# ex4
arr1 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
# ex5
arr1_ex5 = arr1.copy()
arr1_ex5[arr1_ex5 > 5] = 0
arr1_ex5

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])